// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkWifi.InfrastructureServices.Gateways.Database;

namespace ParkWifi.WebService.Migrations
{
    [DbContext(typeof(ParkWifiContext))]
    [Migration("20200528225334_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ParkWifi.DomainObjects.parkwifi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkName")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<string>("wifiName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParkWifis");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Точка доступа №337",
                            ParkName = "Государственное автономное учреждение культуры города Москвы «Государственный историко-архитектурный и природно-ландшафтный музей-заповедник Кузьминки-Люблино, Парк Кузбминки",
                            status = "действует",
                            wifiName = "Moscow_WiFi_Free"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Точка доступа №338",
                            ParkName = "Государственное автономное учреждение культуры города Москвы «Государственный историко-архитектурный и природно-ландшафтный музей-заповедник Кузьминки-Люблино, Парк Кузбминки",
                            status = "действует",
                            wifiName = "Moscow_WiFi_Free"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Точка доступа №339",
                            ParkName = "Государственное автономное учреждение культуры города Москвы «Государственный историко-архитектурный и природно-ландшафтный музей-заповедник Кузьминки-Люблино, Парк Кузбминки",
                            status = "действует",
                            wifiName = "Moscow_WiFi_Free"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Точка доступа №340",
                            ParkName = "Государственное автономное учреждение культуры города Москвы «Государственный историко-архитектурный и природно-ландшафтный музей-заповедник Кузьминки-Люблино, Парк Кузбминки",
                            status = "действует",
                            wifiName = "Moscow_WiFi_Free"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Точка доступа №267",
                            ParkName = "Государственное автономное учреждение культуры города Москвы «Парк культуры и отдыха «Бабушкинский»",
                            status = "действует",
                            wifiName = "Moscow_WiFi_Free"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
