// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkWiFi.InfrastructureServices.Gateways.Database;

namespace ManagementOrganizations.WebService.Migrations
{
    [DbContext(typeof(ParkWiFiContext))]
    [Migration("20200516133210_PWInitial")]
    partial class PWInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ParkWiFi.DomainObjects.ParkWiFi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkName")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<string>("wifiName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParkWiFis");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Точка доступа №337",
                            ParkName = "Государственное автономное учреждение культуры города Москвы «Государственный историко-архитектурный и природно-ландшафтный музей-заповедник Кузьминки-Люблино, Парк Кузбминки",
                            status = "действует",
                            wifiName = "Moscow_WiFi_Free"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
